Repository ironcore-dev/cloud-provider-metal, pull requests merged in 2024-08, with the labels that each got.

#9 Fix Makefile References
  Makefile
Labels: bug, size/S

#10 Add `kustomizations` to deploy CCM
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/service.yaml
  config/rbac/cluster_role.yaml
  config/rbac/cluster_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/serviceaccount.yaml
  pkg/cloudprovider/metal/cloud.go
  pkg/cloudprovider/metal/instances_v2.go
Labels: enhancement, size/L

#11 Use `SystemUUID` in `Node` status to determine `ServerClaim`
  .github/workflows/golangci-lint.yml
  Makefile
  cmd/metal-cloud-controller-manager/main.go
  pkg/cloudprovider/metal/instances_v2.go
  pkg/cloudprovider/metal/instances_v2_test.go
  pkg/cloudprovider/metal/suite_test.go
Labels: enhancement, size/L

#12 Fix missing `clusterrole` for `Nodes`
  config/rbac/cluster_role.yaml
Labels: bug, size/XS

#13 Bump `k8s.io/*` deps to `v0.30.4`
  Makefile
  go.mod
  go.sum
Labels: size/M, chore
