Repository ironcore-dev/cloud-provider-metal, pull requests merged in 2025-04, with the labels that each got.

#74 Add `metal.ironcore.dev/power-off` annotation
  pkg/cloudprovider/metal/constants.go
  pkg/cloudprovider/metal/instances_v2.go
  pkg/cloudprovider/metal/instances_v2_test.go
Labels: enhancement, size/L

#79 Retrieve node ip addresses via owning ServerClaim
  pkg/cloudprovider/metal/constants.go
  pkg/cloudprovider/metal/instances_v2.go
Labels: size/S

#80 Refactor IP address claim labels to use separate name and namespace keys
  pkg/cloudprovider/metal/constants.go
  pkg/cloudprovider/metal/instances_v2.go
Labels: size/S

#82 Add logging for additional `Server` labels
  pkg/cloudprovider/metal/instances_v2.go
Labels: enhancement, size/XS

#84 Update `k8s.io/*` to v0.32 in tests
  .github/workflows/publish-docker.yml
  Makefile
  go.mod
  pkg/cloudprovider/metal/suite_test.go
Labels: size/S, chore
